"""add photo_base64 to learners

Revision ID: 0382cee2bf4e
Revises: ad4dada2c3dd
Create Date: 2026-08-27 15:15:23.172568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0382cee2bf4e'
down_revision = 'ad4dada2c3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_base64', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.drop_column('photo_base64')

    # ### end Alembic commands ###
