"""add reports table

Revision ID: 4aab0f0a420b
Revises: a8a205d5f9f5
Create Date: 2026-07-24 18:13:02.058303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aab0f0a420b'
down_revision = 'a8a205d5f9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('coordinator_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coordinator_id'], ['coordinators.coordinator_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.hub_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
