"""add account lockout fields to coordinator

Revision ID: 92792e8c1547
Revises: ad802bbf96be
Create Date: 2026-07-27 13:40:17.158908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92792e8c1547'
down_revision = 'ad802bbf96be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_failed_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinators', schema=None) as batch_op:
        batch_op.drop_column('last_failed_login_at')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
