"""initial tables

Revision ID: a8a205d5f9f5
Revises: 
Create Date: 2026-07-23 13:56:23.421560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a205d5f9f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubs',
    sa.Column('hub_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('hub_id')
    )
    op.create_table('cohorts',
    sa.Column('cohort_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('min_attendance_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.hub_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cohort_id')
    )
    op.create_table('coordinators',
    sa.Column('coordinator_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.hub_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coordinator_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('learners',
    sa.Column('learner_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('seg_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('nfc_uid', sa.String(length=100), nullable=True),
    sa.Column('fingerprint_enrolled', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id'),
    sa.UniqueConstraint('seg_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('coordinator_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('checkin_open', sa.Boolean(), nullable=False),
    sa.Column('checkout_open', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coordinator_id'], ['coordinators.coordinator_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('attendance_records',
    sa.Column('record_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('verification_method', sa.String(length=20), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.CheckConstraint("verification_method IN ('fingerprint', 'nfc')", name='check_verification_method'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.learner_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('session_id', 'learner_id', name='uq_session_learner')
    )
    op.create_table('nfc_cards',
    sa.Column('card_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.learner_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfc_cards')
    op.drop_table('attendance_records')
    op.drop_table('sessions')
    op.drop_table('learners')
    op.drop_table('coordinators')
    op.drop_table('cohorts')
    op.drop_table('hubs')
    # ### end Alembic commands ###
