"""add audit_logs table

Revision ID: ad802bbf96be
Revises: 4aab0f0a420b
Create Date: 2026-07-26 13:41:40.426812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad802bbf96be'
down_revision = '4aab0f0a420b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('coordinator_id', sa.UUID(), nullable=True),
    sa.Column('hub_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['coordinators.coordinator_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.hub_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
