"""v1.1 initial schema with email auth

Revision ID: b0d62edc9ba7
Revises: 
Create Date: 2026-08-06 09:28:51.464239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d62edc9ba7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='admin', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    op.create_table('email_verifications',
    sa.Column('verification_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('verification_id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_email'), ['email'], unique=False)

    op.create_table('hubs',
    sa.Column('hub_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('hub_id')
    )
    op.create_table('cohorts',
    sa.Column('cohort_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('min_attendance_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.hub_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cohort_id')
    )
    op.create_table('coordinators',
    sa.Column('coordinator_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='coordinator', nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_failed_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.hub_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coordinator_id')
    )
    with op.batch_alter_table('coordinators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coordinators_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('coordinator_id', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('hub_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coordinator_id'], ['coordinators.coordinator_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.hub_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('learners',
    sa.Column('learner_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('seg_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('nfc_uid', sa.String(length=100), nullable=True),
    sa.Column('fingerprint_enrolled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id'),
    sa.UniqueConstraint('seg_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('coordinator_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.Column('checkin_open', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('checkout_open', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coordinator_id'], ['coordinators.coordinator_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('attendance_records',
    sa.Column('record_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('verification_method', sa.String(length=20), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("verification_method IN ('fingerprint', 'nfc', 'manual')", name='check_verification_method'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.learner_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('session_id', 'learner_id', name='uq_session_learner')
    )
    op.create_table('nfc_cards',
    sa.Column('card_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('hub_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.hub_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.learner_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('coordinator_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='submitted', nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coordinator_id'], ['coordinators.coordinator_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.hub_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('nfc_cards')
    op.drop_table('attendance_records')
    op.drop_table('sessions')
    op.drop_table('learners')
    op.drop_table('audit_logs')
    with op.batch_alter_table('coordinators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coordinators_email'))

    op.drop_table('coordinators')
    op.drop_table('cohorts')
    op.drop_table('hubs')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_email'))

    op.drop_table('email_verifications')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
